[phases]
setup = { nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.mysqli"] }
build = { commands = ["composer install --no-dev"] }
start = { cmd = "vendor/bin/php -S 0.0.0.0:$PORT -t public public/index.php" }