[phases]
setup = { 
  nixPkgs = [
    "php82",                   # PHP 8.2
    "php82Packages.composer",  # Composer
    "php82Extensions.pdo",     # PDO extension
    "php82Extensions.mysqli"   # MySQLi extension
  ] 
}
build = { 
  commands = [
    "composer install --no-dev --ignore-platform-reqs --optimize-autoloader"
  ]
}
start = { 
  cmd = "php -S 0.0.0.0:$PORT -t public public/index.php"
}
